Feat/auth
rajnavadiya972/TH-Task-Backend pull request #1
Opened 2024-01-19 12:56 UTC by rajnavadiya972

feat-User register and User login

2024-01-24 05:54 UTC, AJDev111 requested changes
- remove unnecessary code and consoles.
- Queries should be in the proper folder, not in a model folder.
- for error throws and error with proper message not just with only consoles.

2024-01-29 11:16 UTC, AJDev111 requested changes
Previous comments are still not resolved.

2024-01-29 11:16 UTC, th-jay commented on index.js
> +import { } from "dotenv/config";
justify this

2024-01-29 11:16 UTC, th-jay commented on src/config/database.js
> +const { Client } = pg;
simplify this

2024-01-29 11:25 UTC, rajnavadiya972 commented on index.js
> +import { } from "dotenv/config";
ok i understand {} from not require.
i made changes its only  import "dotenv/config"

2024-01-29 11:43 UTC, rajnavadiya972 commented on src/config/database.js
> +const { Client } = pg;
when i simplify this it thow an error
import { Client } from 'pg'
         ^^^^^^
SyntaxError: Named export 'Client' not found. The requested module 'pg' is a CommonJS module, which may not support all module.exports as named exports. 
CommonJS modules can always be imported via the default export, for example using:
import pkg from 'pg';
const { Client } = pkg;

2024-01-31 12:25 UTC, closed without merging